apiVersion: apps/v1
kind: Deployment
metadata:
  name: primos-thread-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: primos-thread
  template:
    metadata:
      labels:
        app: primos-thread
    spec:
      containers:
      - name: primos-thread
        image: gvs22/primos-threads
